version: '3.6'
### get network
### ifconfig -l | xargs -n1 ipconfig getifaddr
networks:
  app-tier:
    driver: bridge
    
services: 
    db1:
        image: mysql
        platform: linux/amd64 ## For Apple M1 Chip, other platoform please remove this line
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
          - "3306:3306"    
        networks:
          - app-tier      
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
    
    postgres:
        image: postgres
        restart: always
        expose:
          - "5432"
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=root
        ports:
          - "5432:5432"
        networks:
          - app-tier      
    
        volumes: 
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

# below is for MySql
    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080

    pgadmin-compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "test123!"
        ports: 
            - "16543:80"
        depends_on: 
            - postgres    
